"""
Shared LLM client for all agents.

Exposes two interfaces:
- `get_chat_model()` — LangChain ChatOpenAI for use in LangGraph graphs
- `chat()` — thin wrapper for one-shot calls without LangGraph
"""

from __future__ import annotations

from functools import lru_cache

from agents.config import AGENT_MODEL, AGENT_TEMPERATURE, BEDROCK_BASE_URL, BEDROCK_PROJECT


@lru_cache(maxsize=1) #keep reusing the same object generated by the aws cred for every subsequent call.
def get_chat_model():
    """bcz of this function the agent participates in the whole ReAct loop(stateful asf)"""
    """Return a LangChain ChatOpenAI pointed at AWS Bedrock, and not openai itself."""
    from aws_bedrock_token_generator import provide_token
    from langchain_openai import ChatOpenAI

    return ChatOpenAI(
        model=AGENT_MODEL,
        temperature=AGENT_TEMPERATURE,
        openai_api_key=provide_token(),
        openai_api_base=BEDROCK_BASE_URL,
        model_kwargs={"extra_headers": {"OpenAI-Project": BEDROCK_PROJECT}},
    )


def chat(messages: list[dict], **kwargs) -> str:
    """One-shot chat call. messages is a list of {role, content} dicts."""
    from langchain_core.messages import HumanMessage, SystemMessage

    lc_messages = []
    for m in messages:
        if m["role"] == "system":
            lc_messages.append(SystemMessage(content=m["content"]))
        else:
            lc_messages.append(HumanMessage(content=m["content"]))

    response = get_chat_model().invoke(lc_messages, **kwargs)
    return response.content
